version: '1'

services: 
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '5173:5173'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      CHOKIDAR_USEPOLLING: true